### ISSUE TITLE
Implement IP based rate limiting

### ISSUE THREAD

**Issue by snorremd** [pilsprog/paraply2#1]
In order to prevent spam we should implement rate limiting, probably based on IP numbers. This can be done by creating an index in ElasticSearch where each document represents an IP (approximated user), a timestamp (when the user of the ip added an event), the url added, and so forth. Each request can represent one event add-request.

Each time a new request ticks in we can check the timestamp for when the IP was last used to add an event. We can also check how many events the IP tried to add the last five minutes (or some other value). These two properties will probably be enough to prevent the worst types of spam. Perhaps we could redirect the users to https://en.wikipedia.org/wiki/Spam_(food) if they try inserting to many events at once.

**Comment by technocake** [comment]
Er det åpent for å legge inn events uten å authentifisere seg? Ville
lagt rate limit på en user / API token som dermed går på tvers av
botnettet. :p

**Comment by snorremd** [comment]
The event(group) submission form is completely open, no user authentication required. The idea is to make it super simple to add events and event groups. Registering av user or authenticating with Google, Facebook, etc does not a super simple submission form make.

But yes, user/authentication token would solve bot-net issues quite nicely. As a first measure I think rate-limiting a single IP address would be enough for now. The Paraply app only accepts Facebook, Meetup, and Eventbrite events anyway, so bot nets would not have much to gain by spamming us.

**Comment by snorremd** [comment]
Implemented super simple rate limiting in 8acde993b506a93f4bed21c80db236705b0b9b52. Right now it is not configurable, but that can be done if there is a need to set time period and max requests.
